### ISSUE TITLE
Exception when determining access permissions to a site

### ISSUE THREAD

**Issue by atruskie** [QutEcoacoustics/baw-server#333]
```
An ActionView::Template::Error occurred in sites#show:

Access level '[:owner, :reader]' is not in available levels '["owner", "writer", "reader"]'.
lib/modules/access/validate.rb:22:in `level'

...

------------------------------- Backtrace:

lib/modules/access/validate.rb:22:in `level'
lib/modules/access/core.rb:73:in `get_level_name'
app/views/sites/show.html.haml:32:in `block in _app_views_sites_show_html_haml___2432286511837677952_31568600'

```

**Comment by atruskie** [comment]
This error occurred again. Happens for non-admin users, that also are owners for their projects.

```
An ActionView::Template::Error occurred in sites#show:

Access level '[:owner, :reader]' is not in available levels '["owner", "writer", "reader"]'.
lib/modules/access/validate.rb:22:in `level'
------------------------------- Request:

* URL        : https://www.ecosounds.org/projects/xxx/sites/xxx
```

**Comment by atruskie** [comment]
Another case:

```
Access level '[:owner, :reader]' is not in available levels '["owner", "writer", "reader"]'.
lib/modules/access/validate.rb:22:in `level'
```
