### ISSUE TITLE
A NoMethodError occurred in errors#route_error:

### ISSUE THREAD

**Issue by atruskie** [QutEcoacoustics/baw-server#532]
```
A NoMethodError occurred in errors#route_error:

  undefined method `message' for nil:NilClass
  app/modules/include_controller.rb:255:in `render_error'

  app/modules/include_controller.rb:255:in `render_error'
  app/controllers/errors_controller.rb:63:in `route_error'
  app/modules/include_controller.rb:650:in `set_then_reset_user_stamper'
```

URL: https://data.acousticobservatory.org/projects/1

**Comment by atruskie** [comment]
```
A NoMethodError occurred in errors#route_error:

  undefined method `message' for nil:NilClass

        message_based_key = "exception:#{Zlib.crc32("#{exception.class.name}\nmessage:#{exception.message}")}"
                                                                                                 ^^^^^^^^
  app/modules/include_controller.rb:259:in `render_error'
```
