### ISSUE TITLE
An ActiveRecord::StatementInvalid occurred in media#show:

### ISSUE THREAD

**Issue by atruskie** [QutEcoacoustics/baw-server#534]
```
An ActiveRecord::StatementInvalid occurred in media#show:

  PG::ExclusionViolation: ERROR:  conflicting key value violates exclusion constraint "constraint_baw_audio_recording_statistics_non_overlapping"
DETAIL:  Key (audio_recording_id, bucket)=(61510, ["2021-09-16 00:00:00","2021-09-17 00:00:00")) conflicts with existing key (audio_recording_id, bucket)=(61510, ["2021-09-16 00:00:00","2021-09-17 00:00:00")).

  app/modules/baw/arel/upsert_manager.rb:63:in `execute'

  * Parameters : {"end_offset"=>"6091", "start_offset"=>"6081", "format"=>"mp3", "controller"=>"media", "action"=>"show", "audio_recording_id"=>"61510"}


  app/modules/baw/arel/upsert_manager.rb:63:in `execute'
  app/modules/baw/active_record/upsert.rb:23:in `upsert_counter'
  app/models/audio_recording_statistics.rb:48:in `increment_segment'
  app/controllers/media_controller.rb:90:in `update_statistics'
  app/modules/include_controller.rb:650:in `set_then_reset_user_stamper'
```

Could be because of a race condition?

**Comment by atruskie** [comment]
Occurred again: 

```
An ActiveRecord::StatementInvalid occurred in media#show:

  PG::ExclusionViolation: ERROR:  conflicting key value violates exclusion constraint "constraint_baw_audio_recording_statistics_non_overlapping"
DETAIL:  Key (audio_recording_id, bucket)=(44599, ["2021-10-08 00:00:00","2021-10-09 00:00:00")) conflicts with existing key (audio_recording_id, bucket)=(44599, ["2021-10-08 00:00:00","2021-10-09 00:00:00")).

  app/modules/baw/arel/upsert_manager.rb:63:in `execute'
  app/modules/baw/active_record/upsert.rb:23:in `upsert_counter'
  app/models/audio_recording_statistics.rb:48:in `increment_segment'
  app/controllers/media_controller.rb:90:in `update_statistics'
  app/modules/include_controller.rb:650:in `set_then_reset_user_stamper'
```
