### ISSUE TITLE
An ActiveRecord::ConnectionNotEstablished occurred in media#show:

### ISSUE THREAD

**Issue by atruskie** [QutEcoacoustics/baw-server#575]
```

  connection is closed
  app/modules/baw/arel/helpers.rb:26:in `block in upsert_on_conflict_sum'

  app/modules/baw/arel/helpers.rb:26:in `block in upsert_on_conflict_sum'
  app/modules/baw/arel/helpers.rb:23:in `map'
  app/modules/baw/arel/helpers.rb:23:in `upsert_on_conflict_sum'
  app/modules/baw/active_record/upsert.rb:24:in `upsert_counter'
  app/models/statistics/audio_recording_statistics.rb:51:in `increment_segment'
  app/controllers/media_controller.rb:92:in `update_statistics'
  app/modules/include_controller.rb:652:in `set_then_reset_user_stamper'
```

Production seems to semi-regularly fail when updating statistics in the after_action hook. It's not clear to me what the problem is, searches on google reveal nothing.

This has occurred at least 58 times in production - but due to error aggregation has probably happened much more.

**Comment by atruskie** [comment]
Speculatively fixed in https://github.com/QutEcoacoustics/baw-server/commit/4efeef877687e2dc228e7135b7384e1869fa5b2a
